<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerX8Qtbxt\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerX8Qtbxt/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerX8Qtbxt.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerX8Qtbxt\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerX8Qtbxt\App_KernelDevDebugContainer([
    'container.build_hash' => 'X8Qtbxt',
    'container.build_id' => 'b8f6ca20',
    'container.build_time' => 1766844631,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerX8Qtbxt');
